// Package traefik generates dynamic configuration consumed by Traefik's file
// provider and publishes it with atomic file replacement.
package traefik

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/webportdev/webport/internal/route"
)

// Config identifies the managed Traefik resources referenced by generated
// dynamic configuration.
type Config struct {
	EntryPoint   string
	CertResolver string
}

// RouteInfo is the minimal route information needed by Traefik.
type RouteInfo struct {
	Domain string
	Port   int
}

// GenerateDynamicConfig builds a complete file-provider configuration. The
// wildcard certificate declaration is kept even when there are no routes so a
// restart removes stale routers without discarding TLS configuration.
func GenerateDynamicConfig(routes []RouteInfo, cfg Config, baseDomain string) (string, error) {
	if baseDomain == "" {
		return "", fmt.Errorf("base domain is required")
	}
	if cfg.EntryPoint == "" {
		return "", fmt.Errorf("Traefik entrypoint is required")
	}
	if cfg.CertResolver == "" {
		return "", fmt.Errorf("Traefik certificate resolver is required")
	}

	sorted := append([]RouteInfo(nil), routes...)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].Domain == sorted[j].Domain {
			return sorted[i].Port < sorted[j].Port
		}
		return sorted[i].Domain < sorted[j].Domain
	})

	var out strings.Builder
	out.WriteString("# Generated by webport. Do not edit manually.\n")
	if len(sorted) > 0 {
		out.WriteString("http:\n")
		out.WriteString("  routers:\n")
		for _, item := range sorted {
			name := strconv.Quote(item.Domain)
			rule := strconv.Quote(fmt.Sprintf("Host(`%s`)", item.Domain))
			fmt.Fprintf(&out, "    %s:\n", name)
			fmt.Fprintf(&out, "      rule: %s\n", rule)
			fmt.Fprintf(&out, "      entryPoints: [%s]\n", strconv.Quote(cfg.EntryPoint))
			fmt.Fprintf(&out, "      service: %s\n", name)
			out.WriteString("      tls: {}\n")
		}
		out.WriteString("  services:\n")
		for _, item := range sorted {
			name := strconv.Quote(item.Domain)
			fmt.Fprintf(&out, "    %s:\n", name)
			out.WriteString("      loadBalancer:\n")
			out.WriteString("        servers:\n")
			fmt.Fprintf(&out, "          - url: %s\n", strconv.Quote(fmt.Sprintf("http://127.0.0.1:%d", item.Port)))
		}
	}

	out.WriteString("tls:\n")
	out.WriteString("  stores:\n")
	out.WriteString("    default:\n")
	out.WriteString("      defaultGeneratedCert:\n")
	fmt.Fprintf(&out, "        resolver: %s\n", strconv.Quote(cfg.CertResolver))
	out.WriteString("        domain:\n")
	fmt.Fprintf(&out, "          main: %s\n", strconv.Quote("*."+baseDomain))
	return out.String(), nil
}

// RoutesToRouteInfos converts stored routes to generator input.
func RoutesToRouteInfos(routes []route.Route) []RouteInfo {
	infos := make([]RouteInfo, 0, len(routes))
	for _, item := range routes {
		infos = append(infos, RouteInfo{Domain: item.Domain, Port: item.Port})
	}
	return infos
}
