// Package caddy handles Caddyfile generation and reloading for webport.
//
// It provides:
//   - GenerateCaddyfile: Creates Caddyfile content from route info
//   - Writer: Interface for writing Caddyfiles and reloading Caddy
//   - BuildDomain: Constructs domain names from project/branch/base domain
//
// Generated Caddyfiles use atomic writes (write to .tmp, then rename)
// to prevent partial reads during Caddy reload.
package caddy

import (
	"fmt"
	"strings"
	"text/template"
	"time"

	"github.com/webportdev/webport/internal/route"
)

// caddyTemplate is the template for generating the Caddyfile
var caddyTemplate = template.Must(template.New("caddyfile").Parse(`# Generated by webport. Do not edit manually.
# Last updated: {{ .Timestamp }}

{{- if .UseDNSChallenge }}
# Wildcard certificate for base domain using DNS challenge
{{ .WildcardDomain }} {
    tls {
        dns {{ .DNSProviderModule }}{{ if .UseTokenArgument }} {env.{{ .DNSTokenEnvVar }}}{{ end }}
    }
}

{{- end }}
{{- range .Routes }}

{{ .Domain }} {
{{- if .UseDNSChallenge }}
    tls {
        dns {{ .DNSProviderModule }}{{ if .UseTokenArgument }} {env.{{ .DNSTokenEnvVar }}}{{ end }}
    }
{{- end }}
    reverse_proxy localhost:{{ .Port }}
}
{{- end }}
`))

// templateData is the data structure for the Caddyfile template
type templateData struct {
	Routes            []RouteInfo
	Timestamp         string
	UseDNSChallenge   bool
	WildcardDomain    string
	BaseDomain        string
	DNSProviderModule string
	DNSTokenEnvVar    string
	UseTokenArgument  bool
}

// RouteInfo represents the minimal route info needed for Caddyfile generation
type RouteInfo struct {
	Domain            string
	Port              int
	UseDNSChallenge   bool
	DNSProviderModule string
	DNSTokenEnvVar    string
	UseTokenArgument  bool
}

// TLSConfig holds TLS/DNS challenge configuration
type TLSConfig struct {
	// DNS provider for challenges (e.g., "cloudflare", "digitalocean", "route53")
	DNSProvider string
	// DNS provider config module for Caddy (e.g., "cloudflare")
	DNSProviderModule string
	// Environment variable name that holds the DNS provider API token
	DNSTokenEnvVar string
}

// GenerateCaddyfile creates Caddyfile content from route info
func GenerateCaddyfile(routes []RouteInfo, tlsCfg TLSConfig, baseDomain string) (string, error) {
	useDNSChallenge := tlsCfg.DNSProvider != "" && tlsCfg.DNSProviderModule != ""

	// Use provided token env var, or default to provider-based naming
	tokenEnvVar := tlsCfg.DNSTokenEnvVar
	if tlsCfg.DNSProvider == "route53" {
		tokenEnvVar = ""
	} else if tokenEnvVar == "" && tlsCfg.DNSProvider != "" {
		tokenEnvVar = defaultTokenEnvVar(tlsCfg.DNSProvider)
	}
	useTokenArgument := tokenEnvVar != ""

	// Build RouteInfo with TLS settings
	routesWithTLS := make([]RouteInfo, len(routes))
	for i, r := range routes {
		routesWithTLS[i] = RouteInfo{
			Domain:            r.Domain,
			Port:              r.Port,
			UseDNSChallenge:   useDNSChallenge,
			DNSProviderModule: tlsCfg.DNSProviderModule,
			DNSTokenEnvVar:    tokenEnvVar,
			UseTokenArgument:  useTokenArgument,
		}
	}

	data := templateData{
		Routes:            routesWithTLS,
		Timestamp:         timestamp(),
		UseDNSChallenge:   useDNSChallenge,
		WildcardDomain:    fmt.Sprintf("*.%s", baseDomain),
		BaseDomain:        baseDomain,
		DNSProviderModule: tlsCfg.DNSProviderModule,
		DNSTokenEnvVar:    tokenEnvVar,
		UseTokenArgument:  useTokenArgument,
	}

	var buf strings.Builder
	if err := caddyTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("template execution failed: %w", err)
	}

	return buf.String(), nil
}

// defaultTokenEnvVar returns a sensible default env var name for the provider.
// This is only used if WEBPORT_TLS_DNS_TOKEN_ENV_VAR is not set.
func defaultTokenEnvVar(provider string) string {
	switch provider {
	case "cloudflare":
		return "CLOUDFLARE_API_TOKEN"
	case "digitalocean":
		return "DO_AUTH_TOKEN"
	case "route53":
		// Route53 reads AWS credentials directly from Caddy's environment.
		return ""
	}
	// Default to PROVIDER_API_TOKEN pattern
	return fmt.Sprintf("%s_API_TOKEN", strings.ToUpper(strings.ReplaceAll(provider, "-", "_")))
}

// RoutesToRouteInfos converts a slice of route.Route to caddy.RouteInfo
// This helper eliminates duplicate conversion code across the codebase
func RoutesToRouteInfos(routes []route.Route) []RouteInfo {
	infos := make([]RouteInfo, 0, len(routes))
	for _, r := range routes {
		infos = append(infos, RouteInfo{
			Domain: r.Domain,
			Port:   r.Port,
		})
	}
	return infos
}

// BuildDomain constructs the full domain for a route
func BuildDomain(baseDomain, project, branch string) string {
	// Sanitize branch name: replace slashes with dashes
	branchSlug := strings.ReplaceAll(branch, "/", "-")
	return fmt.Sprintf("%s-%s.%s", project, branchSlug, baseDomain)
}

// timestamp returns the current time in a format suitable for the Caddyfile
func timestamp() string {
	return time.Now().Format(time.RFC3339)
}
