package caddy

import (
	"strings"
	"testing"
)

func TestGenerateCaddyfile(t *testing.T) {
	tests := []struct {
		name     string
		routes   []RouteInfo
		contains []string // strings that should be in the output
	}{
		{
			name:     "empty routes",
			routes:   []RouteInfo{},
			contains: []string{"# Generated by webport"},
		},
		{
			name: "single route",
			routes: []RouteInfo{
				{Domain: "myapp-main.example.com", Port: 3000},
			},
			contains: []string{
				"myapp-main.example.com",
				"reverse_proxy localhost:3000",
			},
		},
		{
			name: "multiple routes",
			routes: []RouteInfo{
				{Domain: "app1-main.example.com", Port: 3000},
				{Domain: "app2-dev.example.com", Port: 4000},
				{Domain: "app3-feature.example.com", Port: 5000},
			},
			contains: []string{
				"app1-main.example.com",
				"reverse_proxy localhost:3000",
				"app2-dev.example.com",
				"reverse_proxy localhost:4000",
				"app3-feature.example.com",
				"reverse_proxy localhost:5000",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			output, err := GenerateCaddyfile(tt.routes, TLSConfig{}, "example.com")
			if err != nil {
				t.Fatalf("GenerateCaddyfile() error = %v", err)
			}

			// Check that all expected strings are present
			for _, expected := range tt.contains {
				if !strings.Contains(output, expected) {
					t.Errorf("GenerateCaddyfile() output does not contain %q\nGot:\n%s", expected, output)
				}
			}
		})
	}
}

func TestBuildDomain(t *testing.T) {
	tests := []struct {
		name       string
		baseDomain string
		project    string
		branch     string
		expected   string
	}{
		{
			name:       "simple branch",
			baseDomain: "example.com",
			project:    "myapp",
			branch:     "main",
			expected:   "myapp-main.example.com",
		},
		{
			name:       "branch with slash",
			baseDomain: "example.com",
			project:    "myapp",
			branch:     "feature/auth",
			expected:   "myapp-feature-auth.example.com",
		},
		{
			name:       "branch with multiple slashes",
			baseDomain: "mond.boo",
			project:    "myapp",
			branch:     "feature/auth/oauth",
			expected:   "myapp-feature-auth-oauth.mond.boo",
		},
		{
			name:       "branch with hyphen",
			baseDomain: "example.com",
			project:    "myapp",
			branch:     "feature-auth",
			expected:   "myapp-feature-auth.example.com",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := BuildDomain(tt.baseDomain, tt.project, tt.branch)
			if got != tt.expected {
				t.Errorf("BuildDomain() = %v, want %v", got, tt.expected)
			}
		})
	}
}

func TestGenerateCaddyfileFormat(t *testing.T) {
	routes := []RouteInfo{
		{Domain: "app1.example.com", Port: 3000},
		{Domain: "app2.example.com", Port: 4000},
	}

	output, err := GenerateCaddyfile(routes, TLSConfig{}, "example.com")
	if err != nil {
		t.Fatalf("GenerateCaddyfile() error = %v", err)
	}

	// Check that the output has proper structure
	lines := strings.Split(output, "\n")

	// Should have the header comment
	if !strings.Contains(lines[0], "Generated by webport") {
		t.Error("First line should contain 'Generated by webport'")
	}

	// Check that domains are on their own lines followed by opening brace
	foundApp1 := false
	foundApp2 := false
	for i, line := range lines {
		if strings.Contains(line, "app1.example.com") {
			foundApp1 = true
			// Next non-empty line should have the opening brace or reverse_proxy
			if i+1 < len(lines) && strings.TrimSpace(lines[i+1]) == "{" {
				// Valid format
			} else if i+1 < len(lines) && strings.Contains(lines[i], "{") {
				// Also valid - same line
			} else {
				t.Error("Domain should be followed by opening brace")
			}
		}
		if strings.Contains(line, "app2.example.com") {
			foundApp2 = true
		}
	}

	if !foundApp1 {
		t.Error("app1.example.com not found in output")
	}
	if !foundApp2 {
		t.Error("app2.example.com not found in output")
	}
}

func TestGenerateCaddyfileWithDNSChallenge(t *testing.T) {
	routes := []RouteInfo{
		{Domain: "myapp-main.mond.ooo", Port: 3000},
		{Domain: "myapp-dev.mond.ooo", Port: 4000},
	}

	tlsCfg := TLSConfig{
		DNSProvider:       "cloudflare",
		DNSProviderModule: "cloudflare",
	}

	output, err := GenerateCaddyfile(routes, tlsCfg, "mond.ooo")
	if err != nil {
		t.Fatalf("GenerateCaddyfile() error = %v", err)
	}

	// Should contain wildcard domain block
	if !strings.Contains(output, "*.mond.ooo") {
		t.Error("Output should contain wildcard domain *.mond.ooo")
	}

	// Each route should have tls directive with dns provider
	for _, route := range routes {
		if !strings.Contains(output, "dns cloudflare") {
			t.Errorf("Output should contain 'dns cloudflare' for %s", route.Domain)
		}
	}
}

func TestGenerateCaddyfileWithoutDNSChallenge(t *testing.T) {
	routes := []RouteInfo{
		{Domain: "myapp-main.mond.ooo", Port: 3000},
	}

	// Empty TLS config should use default HTTP challenge
	tlsCfg := TLSConfig{}

	output, err := GenerateCaddyfile(routes, tlsCfg, "mond.ooo")
	if err != nil {
		t.Fatalf("GenerateCaddyfile() error = %v", err)
	}

	// Should NOT contain wildcard domain block
	if strings.Contains(output, "*.mond.ooo") {
		t.Error("Output should NOT contain wildcard domain when DNS challenge is disabled")
	}

	// Should NOT contain tls directive
	if strings.Contains(output, "dns") {
		t.Error("Output should NOT contain 'dns' directive when DNS challenge is disabled")
	}
}

func TestGenerateCaddyfileWithCustomTokenEnvVar(t *testing.T) {
	routes := []RouteInfo{
		{Domain: "myapp.example.com", Port: 3000},
	}

	tlsCfg := TLSConfig{
		DNSProvider:       "cloudflare",
		DNSProviderModule: "cloudflare",
		DNSTokenEnvVar:    "MY_CUSTOM_TOKEN",
	}

	output, err := GenerateCaddyfile(routes, tlsCfg, "example.com")
	if err != nil {
		t.Fatalf("GenerateCaddyfile() error = %v", err)
	}

	// Should contain the custom token env var
	if !strings.Contains(output, "{env.MY_CUSTOM_TOKEN}") {
		t.Errorf("Output should contain custom token env var 'MY_CUSTOM_TOKEN'\nGot:\n%s", output)
	}

	// Should NOT contain the default cloudflare token
	if strings.Contains(output, "CLOUDFLARE_API_TOKEN") {
		t.Error("Output should NOT contain default CLOUDFLARE_API_TOKEN when custom is set")
	}
}

func TestGenerateCaddyfileWithDefaultTokenEnvVar(t *testing.T) {
	routes := []RouteInfo{
		{Domain: "myapp.example.com", Port: 3000},
	}

	tlsCfg := TLSConfig{
		DNSProvider:       "cloudflare",
		DNSProviderModule: "cloudflare",
		// DNSTokenEnvVar left empty - should default
	}

	output, err := GenerateCaddyfile(routes, tlsCfg, "example.com")
	if err != nil {
		t.Fatalf("GenerateCaddyfile() error = %v", err)
	}

	// Should contain the default cloudflare token
	if !strings.Contains(output, "{env.CLOUDFLARE_API_TOKEN}") {
		t.Errorf("Output should contain default 'CLOUDFLARE_API_TOKEN'\nGot:\n%s", output)
	}
}

func TestGenerateCaddyfileWithUnknownProvider(t *testing.T) {
	routes := []RouteInfo{
		{Domain: "myapp.example.com", Port: 3000},
	}

	tlsCfg := TLSConfig{
		DNSProvider:       "mydns",
		DNSProviderModule: "mydns",
		// DNSTokenEnvVar left empty - should use PROVIDER_API_TOKEN pattern
	}

	output, err := GenerateCaddyfile(routes, tlsCfg, "example.com")
	if err != nil {
		t.Fatalf("GenerateCaddyfile() error = %v", err)
	}

	// Should use PROVIDER_API_TOKEN pattern
	if !strings.Contains(output, "{env.MYDNS_API_TOKEN}") {
		t.Errorf("Output should contain 'MYDNS_API_TOKEN' for unknown provider\nGot:\n%s", output)
	}
}

func TestGenerateCaddyfileProviderPresets(t *testing.T) {
	tests := []struct {
		name       string
		config     TLSConfig
		directive  string
		notPresent string
	}{
		{"cloudflare", TLSConfig{DNSProvider: "cloudflare", DNSProviderModule: "cloudflare"}, "dns cloudflare {env.CLOUDFLARE_API_TOKEN}", ""},
		{"digitalocean", TLSConfig{DNSProvider: "digitalocean", DNSProviderModule: "digitalocean"}, "dns digitalocean {env.DO_AUTH_TOKEN}", ""},
		{"route53", TLSConfig{DNSProvider: "route53", DNSProviderModule: "route53", DNSTokenEnvVar: "INCORRECT_TOKEN"}, "dns route53", "dns route53 {env."},
		{"custom single-token provider", TLSConfig{DNSProvider: "custom", DNSProviderModule: "acmedns", DNSTokenEnvVar: "ACMEDNS_TOKEN"}, "dns acmedns {env.ACMEDNS_TOKEN}", ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			output, err := GenerateCaddyfile([]RouteInfo{{Domain: "app.example.com", Port: 3000}}, tt.config, "example.com")
			if err != nil {
				t.Fatalf("GenerateCaddyfile() error = %v", err)
			}
			if !strings.Contains(output, tt.directive) {
				t.Fatalf("output does not contain %q:\n%s", tt.directive, output)
			}
			if tt.notPresent != "" && strings.Contains(output, tt.notPresent) {
				t.Fatalf("output unexpectedly contains %q:\n%s", tt.notPresent, output)
			}
		})
	}
}
